import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';
import { Open_Sans, Roboto_Serif } from 'next/font/google';
import './globals.css';

const robotoserif = Roboto_Serif({
  subsets: ['latin'],
  variable: '--font-roboto-serif',
});
const opensans = Open_Sans({
  subsets: ['latin'],
  variable: '--font-open-sans',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={opensans.className}>
        {/* TODO: Navbar */}
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
